contact_links:
  - name: ğŸ™Œ Contribution Guide
    url: https://github.com/shikijs/shiki/blob/main/CONTRIBUTING.md
    about: Please read through before making contributions.
  - name: ğŸ§‘â€ğŸ’» Contribute to New Grammar
    url: https://github.com/shikijs/textmate-grammars-themes/#add-a-new-grammar
    about: Shiki uses grammars collected by `tm-grammars`. Contribute there will inherit to Shiki.
  - name: ğŸŒˆ Contribute to New Theme
    url: https://github.com/shikijs/textmate-grammars-themes/#add-a-new-grammar
    about: Shiki uses themes collected by `tm-themes`. Contribute there will inherit to Shiki.
  - name: â‰ï¸ Why and How to make a reproduction?
    url: https://antfu.me/posts/why-reproductions-are-required
    about: Reproduction is very important for maintainer to help on your issues!
