name: Deploy npm modules
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: pnpm setup
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.17.0
          run_install: true

      - run: pnpm run update
      - run: pnpm run build

      - run: pnpm run test

      - name: Run E2E tests
        run: pnpm run test:e2e

      - name: Deploy npm Packages
        run: npx pleb publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
