name: 'Update Themes'

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  update-themes:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: yarn install

      - run: mkdir -p tmp/themes/vscode

      # Themes in VS Code
      - uses: actions/checkout@v2
        with:
          repository: microsoft/vscode
          path: tmp/vscode

      - run: |
          cp tmp/vscode/extensions/theme-*/themes/dark*.json tmp/themes/vscode
          cp tmp/vscode/extensions/theme-*/themes/light*.json tmp/themes/vscode
          cp tmp/vscode/extensions/theme-*/themes/monokai*.json tmp/themes/vscode
          cp tmp/vscode/extensions/theme-*/themes/solarized*.json tmp/themes/vscode

      # Themes on GitHub
      - run: node scripts/pullThemesFromGitHub.js

      # Material theme
      - uses: actions/checkout@v2
        with:
          repository: material-theme/vsc-material-theme
          path: tmp/vsc-material-theme

      - run: |
          yarn install
          yarn build:ts
          yarn build:generate-themes
        working-directory: tmp/vsc-material-theme

      - run: |
          rm tmp/vsc-material-theme/build/themes/*High-Contrast.json
          cp tmp/vsc-material-theme/build/themes/*.json tmp/themes

      # GitHub theme
      - uses: actions/checkout@v2
        with:
          repository: primer/github-vscode-theme
          path: tmp/github-vscode-theme

      - run: |
          npm install
          npm run build
        working-directory: tmp/github-vscode-theme

      - run: |
          cp tmp/github-vscode-theme/themes/* tmp/themes

      - name: Normalize paths
        run: |
          node scripts/normalizeVSCThemePaths.js
          node scripts/normalizeThemePaths.js

      - name: Move files
        run: |
          rm -rf packages/shiki/themes/*
          cp tmp/themes/*.json packages/shiki/themes

      - name: Update `themes` source
        run: node scripts/updateThemeSrc.js

      - run: |
          if [[ `git status --porcelain` ]]; then
            git config user.name "Pine Wu"
            git config user.email octref@gmail.com
            git status
            git add -A
            git commit -m "Update themes"
            git push
          else
            echo "no changes"
          fi
